"""add crawl rules

Revision ID: 60153355738a
Revises: a53300a12f28
Create Date: 2025-12-04 15:23:28.973175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60153355738a'
down_revision = 'a53300a12f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('title_xpath', sa.String(length=500), nullable=True),
    sa.Column('content_xpath', sa.String(length=500), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_rules')
    # ### end Alembic commands ###
