"""add crawl items

Revision ID: a53300a12f28
Revises: 715d5b277a6a
Create Date: 2025-12-04 10:47:50.617256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53300a12f28'
down_revision = '715d5b277a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('deep_crawled', sa.Boolean(), nullable=True),
    sa.Column('deep_cover', sa.Text(), nullable=True),
    sa.Column('deep_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_items')
    # ### end Alembic commands ###
