"""add article details

Revision ID: da228753bb0b
Revises: 60153355738a
Create Date: 2025-12-04 15:57:00.063421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da228753bb0b'
down_revision = '60153355738a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['crawl_item_id'], ['crawl_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_details')
    # ### end Alembic commands ###
